### ISSUE TITLE
获取文件信息与文档描述不符

### ISSUE THREAD

**Issue by chouney** [upyun/java-sdk#19]
api:[获取文件信息](https://github.com/upyun/java-sdk#%E8%8E%B7%E5%8F%96%E6%96%87%E4%BB%B6%E4%BF%A1%E6%81%AF)，上面说的是当指定文件不存在时返回null。但是实际上当不存在时会抛出异常：
```
Caused by: java.io.FileNotFoundException: http://v0.api.upyun.com/xxxxxx/path/to/file
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at main.java.com.UpYun.getText(UpYun.java:906)
```
因为上传文件会存在覆盖问题，因此需要使用该api来进行文件判定（文档上面是这样写的）。
个人感觉在**业务逻辑当中通过异常来进行判断**不太优雅，可能**使得业务逻辑的异常和真正出现的异常相混淆而出错**。建议修复此问题

**Comment by 594904020** [comment]
我也遇到了同样的问题，有什么解决方法吗
